import Image from "next/image";
import type { Metadata } from "next";
import "./globals.css";
import { Button } from "@/components/button";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className="bg-black-dark text-white relative z-0 flex h-full w-full overflow-hidden">
        <nav className="bg-black border-r border-black-light w-64 flex-shrink-0 overflow-x-hidden h-screen p-4">
          <h1>Linkedoc</h1>
          <Link href="/document/new">
            <Button
              size="sm"
              fullWidth={true}
              className="flex items-center justify-center"
            >
              <Image
                src="/svg/file-plus.svg"
                alt="New document"
                width={18}
                height={18}
              />
              <span className="ml-3">New document</span>
            </Button>
          </Link>
        </nav>
        <main className="relative flex h-full w-full flex-1 p-4">
          {children}
        </main>
      </body>
    </html>
  );
};

export default RootLayout;
